feat: [HDH-494]: Add file count warnings to pre-commit checks (#101229)
* f07b6a HDH-494 Hide pre-commit noisy logs

* 597736 HDH-494 Hide pre-commit noisy logs

* ab1d12 HDH-494 Add file count warnings to pre-commit checks

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,6 +3,11 @@
           Reset='\033[0m'
 echo "Running pre-commit scripts..."
 
+bash .husky/file-count-check.sh
+if [ $? -ne 0 ]; then
+  echo "${Red}File count check failed. Aborting commit.${Reset}"
+  exit 1
+fi
 
 bash .husky/kebab-case-checker.sh
 if [ $? -ne 0 ]; then
@@ -10,7 +15,7 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-yarn test
+npm_config_loglevel=error yarn --silent test
 if [ $? -ne 0 ]; then
   echo "${Red}Tests failed. Aborting commit.${Reset}"
   exit 1
